[package]
name = "slicer"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = "0.20.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.5.4"
lazy_static = "1.4.0"
thiserror = "1.0.31"

[build-dependencies]
cc = "1.0.73"
rayon = "1.5.2"
