on: [push]

name: CI

jobs:
  build_and_test:
    name: SCE Engine Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-07-28  # Required for datatest
          override: true
      - name: Install protobuf
        run: sudo apt-get install -y protobuf-compiler
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            sce/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path sce/Cargo.toml  # https://github.com/actions-rs/cargo/issues/6
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path sce/Cargo.toml  # https://github.com/actions-rs/cargo/issues/6