on: [push]

name: CI

jobs:
  build_and_test:
    name: SCE Engine Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly  # Required for datatest
      - uses: actions-rs/cargo@v1
        with:
          command: test
        working-directory: sce/
